clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 89.169.156.224
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.43.177
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "/home/ansible/.ssh/id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"
